// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cursors.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getCursor = `-- name: GetCursor :one
SELECT chain_id, block_number, block_hash, state, updated_at
FROM cursors
WHERE chain_id = $1
`

type GetCursorRow struct {
	ChainID     string        `db:"chain_id" json:"chain_id"`
	BlockNumber int64         `db:"block_number" json:"block_number"`
	BlockHash   string        `db:"block_hash" json:"block_hash"`
	State       string        `db:"state" json:"state"`
	UpdatedAt   sql.NullInt64 `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetCursor(ctx context.Context, chainID string) (GetCursorRow, error) {
	row := q.db.QueryRowContext(ctx, getCursor, chainID)
	var i GetCursorRow
	err := row.Scan(
		&i.ChainID,
		&i.BlockNumber,
		&i.BlockHash,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCursorBlock = `-- name: UpdateCursorBlock :exec
UPDATE cursors 
SET block_number = $1, block_hash = $2, updated_at = $4
WHERE chain_id = $3
`

type UpdateCursorBlockParams struct {
	BlockNumber int64         `db:"block_number" json:"block_number"`
	BlockHash   string        `db:"block_hash" json:"block_hash"`
	ChainID     string        `db:"chain_id" json:"chain_id"`
	UpdatedAt   sql.NullInt64 `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateCursorBlock(ctx context.Context, arg UpdateCursorBlockParams) error {
	_, err := q.db.ExecContext(ctx, updateCursorBlock,
		arg.BlockNumber,
		arg.BlockHash,
		arg.ChainID,
		arg.UpdatedAt,
	)
	return err
}

const updateCursorState = `-- name: UpdateCursorState :exec
UPDATE cursors 
SET state = $1, updated_at = $3
WHERE chain_id = $2
`

type UpdateCursorStateParams struct {
	State     string        `db:"state" json:"state"`
	ChainID   string        `db:"chain_id" json:"chain_id"`
	UpdatedAt sql.NullInt64 `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateCursorState(ctx context.Context, arg UpdateCursorStateParams) error {
	_, err := q.db.ExecContext(ctx, updateCursorState, arg.State, arg.ChainID, arg.UpdatedAt)
	return err
}

const upsertCursor = `-- name: UpsertCursor :exec
INSERT INTO cursors (chain_id, block_number, block_hash, state, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (chain_id) DO UPDATE SET
    block_number = EXCLUDED.block_number,
    block_hash = EXCLUDED.block_hash,
    state = EXCLUDED.state,
    updated_at = $5
`

type UpsertCursorParams struct {
	ChainID     string        `db:"chain_id" json:"chain_id"`
	BlockNumber int64         `db:"block_number" json:"block_number"`
	BlockHash   string        `db:"block_hash" json:"block_hash"`
	State       string        `db:"state" json:"state"`
	UpdatedAt   sql.NullInt64 `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertCursor(ctx context.Context, arg UpsertCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertCursor,
		arg.ChainID,
		arg.BlockNumber,
		arg.BlockHash,
		arg.State,
		arg.UpdatedAt,
	)
	return err
}

const upsertCursorBlock = `-- name: UpsertCursorBlock :exec
INSERT INTO cursors (chain_id, block_number, block_hash, state, updated_at)
VALUES ($1, $2, $3, 'scanning', $4)
ON CONFLICT (chain_id) DO UPDATE SET
    block_number = EXCLUDED.block_number,
    block_hash = EXCLUDED.block_hash,
    updated_at = $4
`

type UpsertCursorBlockParams struct {
	ChainID     string        `db:"chain_id" json:"chain_id"`
	BlockNumber int64         `db:"block_number" json:"block_number"`
	BlockHash   string        `db:"block_hash" json:"block_hash"`
	UpdatedAt   sql.NullInt64 `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertCursorBlock(ctx context.Context, arg UpsertCursorBlockParams) error {
	_, err := q.db.ExecContext(ctx, upsertCursorBlock,
		arg.ChainID,
		arg.BlockNumber,
		arg.BlockHash,
		arg.UpdatedAt,
	)
	return err
}
