// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failed_blocks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countFailedBlocks = `-- name: CountFailedBlocks :one
SELECT COUNT(*) 
FROM failed_blocks 
WHERE chain_id = $1 AND status = 'pending'
`

func (q *Queries) CountFailedBlocks(ctx context.Context, chainID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedBlocks, chainID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFailedBlock = `-- name: CreateFailedBlock :exec
INSERT INTO failed_blocks (chain_id, block_number, error_msg, retry_count, status, last_attempt, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateFailedBlockParams struct {
	ChainID     string         `db:"chain_id" json:"chain_id"`
	BlockNumber int64          `db:"block_number" json:"block_number"`
	ErrorMsg    sql.NullString `db:"error_msg" json:"error_msg"`
	RetryCount  int32          `db:"retry_count" json:"retry_count"`
	Status      string         `db:"status" json:"status"`
	LastAttempt sql.NullInt64  `db:"last_attempt" json:"last_attempt"`
	CreatedAt   sql.NullInt64  `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateFailedBlock(ctx context.Context, arg CreateFailedBlockParams) error {
	_, err := q.db.ExecContext(ctx, createFailedBlock,
		arg.ChainID,
		arg.BlockNumber,
		arg.ErrorMsg,
		arg.RetryCount,
		arg.Status,
		arg.LastAttempt,
		arg.CreatedAt,
	)
	return err
}

const getAllFailedBlocks = `-- name: GetAllFailedBlocks :many
SELECT id, chain_id, block_number, error_msg, retry_count, last_attempt, status
FROM failed_blocks
WHERE chain_id = $1 AND status = 'pending'
`

type GetAllFailedBlocksRow struct {
	ID          int32          `db:"id" json:"id"`
	ChainID     string         `db:"chain_id" json:"chain_id"`
	BlockNumber int64          `db:"block_number" json:"block_number"`
	ErrorMsg    sql.NullString `db:"error_msg" json:"error_msg"`
	RetryCount  int32          `db:"retry_count" json:"retry_count"`
	LastAttempt sql.NullInt64  `db:"last_attempt" json:"last_attempt"`
	Status      string         `db:"status" json:"status"`
}

func (q *Queries) GetAllFailedBlocks(ctx context.Context, chainID string) ([]GetAllFailedBlocksRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFailedBlocks, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFailedBlocksRow
	for rows.Next() {
		var i GetAllFailedBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.BlockNumber,
			&i.ErrorMsg,
			&i.RetryCount,
			&i.LastAttempt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextFailedBlock = `-- name: GetNextFailedBlock :one
SELECT id, chain_id, block_number, error_msg, retry_count, last_attempt, status
FROM failed_blocks
WHERE chain_id = $1 AND status = 'pending'
ORDER BY last_attempt ASC
LIMIT 1
`

type GetNextFailedBlockRow struct {
	ID          int32          `db:"id" json:"id"`
	ChainID     string         `db:"chain_id" json:"chain_id"`
	BlockNumber int64          `db:"block_number" json:"block_number"`
	ErrorMsg    sql.NullString `db:"error_msg" json:"error_msg"`
	RetryCount  int32          `db:"retry_count" json:"retry_count"`
	LastAttempt sql.NullInt64  `db:"last_attempt" json:"last_attempt"`
	Status      string         `db:"status" json:"status"`
}

func (q *Queries) GetNextFailedBlock(ctx context.Context, chainID string) (GetNextFailedBlockRow, error) {
	row := q.db.QueryRowContext(ctx, getNextFailedBlock, chainID)
	var i GetNextFailedBlockRow
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.BlockNumber,
		&i.ErrorMsg,
		&i.RetryCount,
		&i.LastAttempt,
		&i.Status,
	)
	return i, err
}

const incrementFailedBlockRetry = `-- name: IncrementFailedBlockRetry :exec
UPDATE failed_blocks 
SET retry_count = retry_count + 1, last_attempt = $2
WHERE id = $1
`

type IncrementFailedBlockRetryParams struct {
	ID          int32         `db:"id" json:"id"`
	LastAttempt sql.NullInt64 `db:"last_attempt" json:"last_attempt"`
}

func (q *Queries) IncrementFailedBlockRetry(ctx context.Context, arg IncrementFailedBlockRetryParams) error {
	_, err := q.db.ExecContext(ctx, incrementFailedBlockRetry, arg.ID, arg.LastAttempt)
	return err
}

const markFailedBlockResolved = `-- name: MarkFailedBlockResolved :exec
UPDATE failed_blocks 
SET status = 'resolved' 
WHERE id = $1
`

func (q *Queries) MarkFailedBlockResolved(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markFailedBlockResolved, id)
	return err
}
