// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: missing_blocks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPendingMissingBlocks = `-- name: CountPendingMissingBlocks :one
SELECT COUNT(*) 
FROM missing_blocks 
WHERE chain_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingMissingBlocks(ctx context.Context, chainID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingMissingBlocks, chainID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMissingBlock = `-- name: CreateMissingBlock :exec
INSERT INTO missing_blocks (chain_id, from_block, to_block, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
`

type CreateMissingBlockParams struct {
	ChainID   string `db:"chain_id" json:"chain_id"`
	FromBlock int64  `db:"from_block" json:"from_block"`
	ToBlock   int64  `db:"to_block" json:"to_block"`
	Status    string `db:"status" json:"status"`
}

func (q *Queries) CreateMissingBlock(ctx context.Context, arg CreateMissingBlockParams) error {
	_, err := q.db.ExecContext(ctx, createMissingBlock,
		arg.ChainID,
		arg.FromBlock,
		arg.ToBlock,
		arg.Status,
	)
	return err
}

const getNextMissingBlock = `-- name: GetNextMissingBlock :one
SELECT id, chain_id, from_block, to_block, status, created_at, updated_at
FROM missing_blocks
WHERE chain_id = $1 AND status = 'pending'
ORDER BY from_block ASC
LIMIT 1
`

type GetNextMissingBlockRow struct {
	ID        int32         `db:"id" json:"id"`
	ChainID   string        `db:"chain_id" json:"chain_id"`
	FromBlock int64         `db:"from_block" json:"from_block"`
	ToBlock   int64         `db:"to_block" json:"to_block"`
	Status    string        `db:"status" json:"status"`
	CreatedAt sql.NullInt64 `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullInt64 `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetNextMissingBlock(ctx context.Context, chainID string) (GetNextMissingBlockRow, error) {
	row := q.db.QueryRowContext(ctx, getNextMissingBlock, chainID)
	var i GetNextMissingBlockRow
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.FromBlock,
		&i.ToBlock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingMissingBlocks = `-- name: GetPendingMissingBlocks :many
SELECT id, chain_id, from_block, to_block, status
FROM missing_blocks
WHERE chain_id = $1 AND status = 'pending'
ORDER BY from_block ASC
LIMIT 1000
`

type GetPendingMissingBlocksRow struct {
	ID        int32  `db:"id" json:"id"`
	ChainID   string `db:"chain_id" json:"chain_id"`
	FromBlock int64  `db:"from_block" json:"from_block"`
	ToBlock   int64  `db:"to_block" json:"to_block"`
	Status    string `db:"status" json:"status"`
}

func (q *Queries) GetPendingMissingBlocks(ctx context.Context, chainID string) ([]GetPendingMissingBlocksRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingMissingBlocks, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingMissingBlocksRow
	for rows.Next() {
		var i GetPendingMissingBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.FromBlock,
			&i.ToBlock,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingBlockCompleted = `-- name: MarkMissingBlockCompleted :exec
UPDATE missing_blocks SET status = 'completed', updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkMissingBlockCompleted(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markMissingBlockCompleted, id)
	return err
}

const markMissingBlockFailed = `-- name: MarkMissingBlockFailed :exec
UPDATE missing_blocks SET status = 'failed', error_msg = $2, updated_at = NOW() WHERE id = $1
`

type MarkMissingBlockFailedParams struct {
	ID       int32          `db:"id" json:"id"`
	ErrorMsg sql.NullString `db:"error_msg" json:"error_msg"`
}

func (q *Queries) MarkMissingBlockFailed(ctx context.Context, arg MarkMissingBlockFailedParams) error {
	_, err := q.db.ExecContext(ctx, markMissingBlockFailed, arg.ID, arg.ErrorMsg)
	return err
}

const markMissingBlockProcessing = `-- name: MarkMissingBlockProcessing :exec
UPDATE missing_blocks SET status = 'processing', updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkMissingBlockProcessing(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markMissingBlockProcessing, id)
	return err
}
