// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Block struct {
	ChainID        string                `db:"chain_id" json:"chain_id"`
	BlockNumber    int64                 `db:"block_number" json:"block_number"`
	BlockHash      string                `db:"block_hash" json:"block_hash"`
	ParentHash     string                `db:"parent_hash" json:"parent_hash"`
	BlockTimestamp int64                 `db:"block_timestamp" json:"block_timestamp"`
	TxCount        int32                 `db:"tx_count" json:"tx_count"`
	Status         string                `db:"status" json:"status"`
	Metadata       pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	CreatedAt      sql.NullInt64         `db:"created_at" json:"created_at"`
}

type Cursor struct {
	ChainID     string                `db:"chain_id" json:"chain_id"`
	BlockNumber int64                 `db:"block_number" json:"block_number"`
	BlockHash   string                `db:"block_hash" json:"block_hash"`
	State       string                `db:"state" json:"state"`
	Metadata    pqtype.NullRawMessage `db:"metadata" json:"metadata"`
	CreatedAt   sql.NullInt64         `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullInt64         `db:"updated_at" json:"updated_at"`
}

type FailedBlock struct {
	ID          int32          `db:"id" json:"id"`
	ChainID     string         `db:"chain_id" json:"chain_id"`
	BlockNumber int64          `db:"block_number" json:"block_number"`
	ErrorMsg    sql.NullString `db:"error_msg" json:"error_msg"`
	RetryCount  int32          `db:"retry_count" json:"retry_count"`
	LastAttempt sql.NullInt64  `db:"last_attempt" json:"last_attempt"`
	Status      string         `db:"status" json:"status"`
	CreatedAt   sql.NullInt64  `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullInt64  `db:"updated_at" json:"updated_at"`
}

type MissingBlock struct {
	ID        int32          `db:"id" json:"id"`
	ChainID   string         `db:"chain_id" json:"chain_id"`
	FromBlock int64          `db:"from_block" json:"from_block"`
	ToBlock   int64          `db:"to_block" json:"to_block"`
	Status    string         `db:"status" json:"status"`
	Attempts  int32          `db:"attempts" json:"attempts"`
	ErrorMsg  sql.NullString `db:"error_msg" json:"error_msg"`
	CreatedAt sql.NullInt64  `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullInt64  `db:"updated_at" json:"updated_at"`
}

type Transaction struct {
	ChainID        string                `db:"chain_id" json:"chain_id"`
	TxHash         string                `db:"tx_hash" json:"tx_hash"`
	BlockNumber    int64                 `db:"block_number" json:"block_number"`
	BlockHash      string                `db:"block_hash" json:"block_hash"`
	TxIndex        int32                 `db:"tx_index" json:"tx_index"`
	FromAddress    string                `db:"from_address" json:"from_address"`
	ToAddress      sql.NullString        `db:"to_address" json:"to_address"`
	Value          sql.NullString        `db:"value" json:"value"`
	GasUsed        sql.NullInt64         `db:"gas_used" json:"gas_used"`
	GasPrice       sql.NullString        `db:"gas_price" json:"gas_price"`
	Status         sql.NullString        `db:"status" json:"status"`
	BlockTimestamp int64                 `db:"block_timestamp" json:"block_timestamp"`
	RawData        pqtype.NullRawMessage `db:"raw_data" json:"raw_data"`
	CreatedAt      sql.NullInt64         `db:"created_at" json:"created_at"`
}

type WalletAddress struct {
	ID          int32         `db:"id" json:"id"`
	Address     string        `db:"address" json:"address"`
	NetworkType string        `db:"network_type" json:"network_type"`
	Standard    string        `db:"standard" json:"standard"`
	CreatedAt   sql.NullInt64 `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullInt64 `db:"updated_at" json:"updated_at"`
}
