// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountFailedBlocks(ctx context.Context, chainID string) (int64, error)
	CountPendingMissingBlocks(ctx context.Context, chainID string) (int64, error)
	CreateBlock(ctx context.Context, arg CreateBlockParams) error
	CreateFailedBlock(ctx context.Context, arg CreateFailedBlockParams) error
	CreateMissingBlock(ctx context.Context, arg CreateMissingBlockParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	CreateWalletAddress(ctx context.Context, arg CreateWalletAddressParams) error
	DeleteBlocksInRange(ctx context.Context, arg DeleteBlocksInRangeParams) error
	DeleteBlocksOlderThan(ctx context.Context, arg DeleteBlocksOlderThanParams) error
	DeleteTransactionsByBlock(ctx context.Context, arg DeleteTransactionsByBlockParams) error
	DeleteTransactionsOlderThan(ctx context.Context, arg DeleteTransactionsOlderThanParams) error
	FindGaps(ctx context.Context, arg FindGapsParams) ([]FindGapsRow, error)
	GetAllFailedBlocks(ctx context.Context, chainID string) ([]GetAllFailedBlocksRow, error)
	GetBlockByHash(ctx context.Context, arg GetBlockByHashParams) (Block, error)
	GetBlockByNumber(ctx context.Context, arg GetBlockByNumberParams) (Block, error)
	GetCursor(ctx context.Context, chainID string) (GetCursorRow, error)
	GetLatestBlock(ctx context.Context, chainID string) (Block, error)
	GetNextFailedBlock(ctx context.Context, chainID string) (GetNextFailedBlockRow, error)
	GetNextMissingBlock(ctx context.Context, chainID string) (GetNextMissingBlockRow, error)
	GetPendingMissingBlocks(ctx context.Context, chainID string) ([]GetPendingMissingBlocksRow, error)
	GetTransactionByHash(ctx context.Context, arg GetTransactionByHashParams) (Transaction, error)
	GetTransactionsByBlock(ctx context.Context, arg GetTransactionsByBlockParams) ([]Transaction, error)
	GetWalletAddress(ctx context.Context, address string) (WalletAddress, error)
	IncrementFailedBlockRetry(ctx context.Context, arg IncrementFailedBlockRetryParams) error
	ListWalletAddresses(ctx context.Context) ([]WalletAddress, error)
	MarkFailedBlockResolved(ctx context.Context, id int32) error
	MarkMissingBlockCompleted(ctx context.Context, id int32) error
	MarkMissingBlockFailed(ctx context.Context, arg MarkMissingBlockFailedParams) error
	MarkMissingBlockProcessing(ctx context.Context, id int32) error
	UpdateBlockStatus(ctx context.Context, arg UpdateBlockStatusParams) error
	UpdateCursorBlock(ctx context.Context, arg UpdateCursorBlockParams) error
	UpdateCursorState(ctx context.Context, arg UpdateCursorStateParams) error
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
	UpsertCursor(ctx context.Context, arg UpsertCursorParams) error
	UpsertCursorBlock(ctx context.Context, arg UpsertCursorBlockParams) error
}

var _ Querier = (*Queries)(nil)
