// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_addresses.sql

package sqlc

import (
	"context"
)

const createWalletAddress = `-- name: CreateWalletAddress :exec
INSERT INTO wallet_addresses (address, network_type, standard)
VALUES ($1, $2, $3)
ON CONFLICT (address, network_type) DO UPDATE
SET
    standard = EXCLUDED.standard
`

type CreateWalletAddressParams struct {
	Address     string `db:"address" json:"address"`
	NetworkType string `db:"network_type" json:"network_type"`
	Standard    string `db:"standard" json:"standard"`
}

func (q *Queries) CreateWalletAddress(ctx context.Context, arg CreateWalletAddressParams) error {
	_, err := q.db.ExecContext(ctx, createWalletAddress, arg.Address, arg.NetworkType, arg.Standard)
	return err
}

const getWalletAddress = `-- name: GetWalletAddress :one
SELECT id, address, network_type, standard, created_at, updated_at
FROM wallet_addresses
WHERE address = $1
`

func (q *Queries) GetWalletAddress(ctx context.Context, address string) (WalletAddress, error) {
	row := q.db.QueryRowContext(ctx, getWalletAddress, address)
	var i WalletAddress
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.NetworkType,
		&i.Standard,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWalletAddresses = `-- name: ListWalletAddresses :many
SELECT id, address, network_type, standard, created_at, updated_at
FROM wallet_addresses
`

func (q *Queries) ListWalletAddresses(ctx context.Context) ([]WalletAddress, error) {
	rows, err := q.db.QueryContext(ctx, listWalletAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletAddress
	for rows.Next() {
		var i WalletAddress
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.NetworkType,
			&i.Standard,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
