// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_addresses.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createWalletAddress = `-- name: CreateWalletAddress :exec
INSERT INTO wallet_addresses (address, network_type, standard, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (address) DO UPDATE SET
    network_type = EXCLUDED.network_type,
    standard = EXCLUDED.standard,
    updated_at = $5
`

type CreateWalletAddressParams struct {
	Address     string        `db:"address" json:"address"`
	NetworkType string        `db:"network_type" json:"network_type"`
	Standard    string        `db:"standard" json:"standard"`
	CreatedAt   sql.NullInt64 `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullInt64 `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateWalletAddress(ctx context.Context, arg CreateWalletAddressParams) error {
	_, err := q.db.ExecContext(ctx, createWalletAddress,
		arg.Address,
		arg.NetworkType,
		arg.Standard,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getWalletAddress = `-- name: GetWalletAddress :one
SELECT id, address, network_type, standard, created_at, updated_at
FROM wallet_addresses
WHERE address = $1
`

func (q *Queries) GetWalletAddress(ctx context.Context, address string) (WalletAddress, error) {
	row := q.db.QueryRowContext(ctx, getWalletAddress, address)
	var i WalletAddress
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.NetworkType,
		&i.Standard,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWalletAddresses = `-- name: ListWalletAddresses :many
SELECT id, address, network_type, standard, created_at, updated_at
FROM wallet_addresses
`

func (q *Queries) ListWalletAddresses(ctx context.Context) ([]WalletAddress, error) {
	rows, err := q.db.QueryContext(ctx, listWalletAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletAddress
	for rows.Next() {
		var i WalletAddress
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.NetworkType,
			&i.Standard,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
